### ISSUE TITLE
Duplicate found in array constants

### ISSUE THREAD

**Issue by dvandersluis** [codeclimate/codeclimate-duplication#112]
Consider the following code:

```ruby
COLORS = %w(#D8E304 #04D215 #0D52D1 #8A0CCF #CD0D74 #DDDDDD #333333 #57032A #990000 #FF6600 #FCD202 #B0DE09 #0D8ECF #2A0CD0 #754DEB #999999)
NAMES = %w(albert barbara claire daniel edgar frank george herbert isador javier killian larry michael nancy oscar peter)
```

The duplication engine returns the following:

```
$ codeclimate analyze -e duplication
Starting analysis
Running duplication: Done!

== app/models/constants.rb (2 issues) ==
1: Similar code found in 1 other location (mass = 18) [duplication]
2: Similar code found in 1 other location (mass = 18) [duplication]

Analysis complete! Found 2 issues.
```

This happens also if using array literals instead of the `%w` macro. If I reduce each array by one the error no longer shows up (mass = 18 is the lowest I could get this to reproduce).

As far as I am concerned this is a false positive -- any reason this is considered duplicate code?

**Comment by pbrisbin** [comment]
Hi @dvandersluis, thanks for reporting this.

Unfortunately, these cases of structural duplication with unique values are an example of things that are obvious to a human but not so obvious to a machine. Furthermore, any steps taken to make cases like this one not appear as duplication would likely result in other cases, that actually are duplication (by a reasonable, but ultimately subjective measure), also not appear as such. We'd be trading a class of false-positives for a class of false-negatives.

We're not giving up on improving the algorithm as much as possible, but addressing this kind of false-positive is as not as cut-and-dry as it might appear, and therefore we don't consider this a bug in the engine (or Flay itself) as it works today.

I would suggest you either increase your configured threshold, or exclude this specific case by fingerprint.

> any reason this is considered duplicate code?

The short answer is because Flay does. Hopefully the longer answer I provided above is useful too. If it's OK with you, I'd like to close this Issue.

**Comment by dvandersluis** [comment]
@pbrisbin Thanks for the info, that does indeed answer my question. We have excluded the fingerprint, so I guess this can be closed!
