### ISSUE TITLE
Add documentation for fingerprints

### ISSUE THREAD

**Issue by gappleto97** [codeclimate/codeclimate-duplication#122]
If I add a fingerprint to exclude, does that ignore just that issue specifically, or *any* issue of the same type?

**Comment by pbrisbin** [comment]
> does that ignore just that issue specifically, or any issue of the same type?

Technically it ignores any issue _with that fingerprint_. The intent is that an issue fingerprint uniquely identifies that specific issue, so I believe the answer to your question is "just that issue specifically". (Depending on how you define "the same type", you may be able to achieve that by excluding by check-name or engine-name.)

It's worth noting that our default fingerprinting algorithm tries to be smart such that (for example) if you make a long method longer that will appear as the same issue getting worse, not one issue being fixed (an 18-line Long Method) and a new issue being created (a 19-line Long Method). Because of this, it is possible (though rare) for two distinct issues to have the same fingerprint. In such a case, ignoring that fingerprint would ignore both.

To complicate matters further, engines are free to implement fingerprinting their own way (maybe they want to take into account the language-specific context that engine may have), so it's hard to say with certainty how fingerprint-based excludes will behave in all cases. You can see how the duplication engine specifically calculates fingerprints [here](https://github.com/codeclimate/codeclimate-duplication/blob/1c118a13b28752e82683b40d610e5b1ee8c41471/lib/cc/engine/analyzers/violation.rb#L83). 

We do have some information about this in our [docs](https://docs.codeclimate.com/docs/marking-false-positives). Fingerprinting is a subtle aspect of our system, and we intend to increase the documentation in this area. That said, I'm not sure having an Issue open on this engine's repository is necessary at this time. Would it be OK with you if I closed it?

**Comment by gappleto97** [comment]
I would. I would also appreciate it if I could get an answer given context.

I have two methods. Both are shortcuts to determine a compression method given a string of that method.

```python
def compress(msg, method):  # takes bytes, returns bytes
    """Shortcut method for compression"""
    if method == flags.gzip:
        return zlib.compress(msg)
    elif method == flags.bz2:
        return bz2.compress(msg)
    elif method == flags.lzma:
        return lzma.compress(msg)
    else:
        raise Exception('Unknown compression method')


def decompress(msg, method):  # takes bytes, returns bytes
    """Shortcut method for decompression"""
    if method == flags.gzip:
        return zlib.decompress(msg, zlib.MAX_WBITS | 32)
    elif method == flags.bz2:
        return bz2.decompress(msg)
    elif method == flags.lzma:
        return lzma.decompress(msg)
    else:
        raise Exception('Unknown decompression method')
```

Duplication was reporting this as similar code, so I added its fingerprint. In this specific instance, would that have effects on any other issues down the line?

**Comment by pbrisbin** [comment]
In the case of the duplication engine, fingerprints are an md5 of file-name, mass, and check-name. check-name is just "Identical" or "Similar" and mass is (basically) the number of nodes in the AST representation of that bit of code (more info [here](https://docs.codeclimate.com/docs/duplication#understand-the-engine)). So for there to be a fingerprint collision, it would have to be with another issue in the same file with the number of AST nodes.

Unfortunately, I can't give you any exact probability, but I wouldn't lose sleep over it. Ignoring duplication issues by fingerprint is a strategy we recommend (and use ourselves) often, and we haven't heard or seen reports of collisions.

Hope this helps.

**Comment by gappleto97** [comment]
Okay, just wanted to make sure, because I seem to remember having some similar issue in the past. Thanks.

**Comment by pbrisbin** [comment]
If you run into trouble with fingerprint collisions, feel free to reach out to [support](https://codeclimate.com/help) and we can dig into the data and try to get to the bottom of any specific examples.
