### ISSUE TITLE
Allow configuration of a "number of instances" threshold

### ISSUE THREAD

**Issue by zspencer** [codeclimate/codeclimate-duplication#302]
In XP, one common practice is to wait for three instances of duplication, so you don't wind up pre-maturely drying something up into a pattern that doesn't have enough instances to inform the decision

It would be nice if there was a way to configure a count threshold similar to a mass threshold so I can decide whether 2 or 3 cases is the right time to think about drying up similar code.

**Comment by wfleming** [comment]
This engine dos support a [`count_threshold` option](https://github.com/codeclimate/codeclimate-duplication#count-threshold), described in the README, @zspencer. That seems like it fits the functionality you're asking for. Is thtat not working for you?

**Comment by zspencer** [comment]
Welp, this is what I get for assuming the online documentation is as-up-to-date as the code documentation :). Thanks for pointing that out! Closing now in pure embarrassment.

**Comment by wfleming** [comment]
No worries, sorry the online docs you were looking at were out of date. For the record, some of the options (like `count_threshod`) currently covered in the README here are semi-deprecated, since we're moving away from configuring duplication under the `plugins` key for a variety of reasons. That said, we haven't yet implemented the new ways we want to support configuration like this with our new style of configuration yet, so we will continue to support this deprecated style of configuration for the forseeable future until we can support the same features with a new style, and then for some period of transistion time afterwards as well, of course.

**Comment by zspencer** [comment]
Yea, I had noticed that codeclimate doesn't encourage the .yml files anymore. I'm sure you'll figure out a way to make it work awesomely :)
