### ISSUE TITLE
Python 3 as default

### ISSUE THREAD

**Issue by m-aciek** [codeclimate/codeclimate-duplication#332]
Currently Python 2 is default Python version in duplication. Python 2 will retire on [1 January 2020](https://pythonclock.org/). Isn't it already the right time to make Python 3 a default?

**Comment by maxjacobson** [comment]
Hi @m-aciek - good question. We have to be sensitive to backwards compatibility, because if we change the default, it will change it for all Code Climate users, which could lead to unexpectedly breaking builds. This can lead us to drag our feet a little bit sometimes. I think for now we'll keep dragging, but please let us know if the documented configuration option doesn't meet your needs for any reason.
