### ISSUE TITLE
Run in verbose mode

### ISSUE THREAD

**Issue by matthisk** [codeclimate/codeclimate-duplication#99]
Is it possible to run this engine using the CodeClimate CLI in some sort of verbose mode. My configuration currently fails because of a timeout, however my setup does exclude all paths with unrelated files (e.g. node_modules). I am curious to see which file this engine is actually running through the analyzer, but cant find any option to show this output.

**Comment by wfleming** [comment]
We don't have any kind of verbose flag support within engines at the moment, @matthisk, sorry. The duplication engine is computationally intensive because it's comparing syntax trees across all of your source files at once, so on large projects it can hit our default time limits.

Those time limits can be adjusted, though. Are you using our CLI or running analysis on codeclimate.com?

**Comment by dblandin** [comment]
As of https://github.com/codeclimate/codeclimate-duplication/pull/109, you should be able to see debug output with the following engine configuration:

```yaml
  duplication:
    enabled: true
    config:
      debug: true
      languages:
      - ruby
```

To see stderr from engines, you should run the CLI in debug mode as well:

```
CODECLIMATE_DEBUG=1 codeclimate analyze
```

source: https://github.com/codeclimate/codeclimate#environment-variables
